apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-namespace-secret-reader
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
---
# Binding for openshift-monitoring namespace to read alertmanager-main
# gather_alertmanager_config.go
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: openshift-monitoring
subjects:
  - kind: ServiceAccount
    namespace: openshift-insights
    name: gather
roleRef:
  kind: ClusterRole
  name: multi-namespace-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
# Binding for openshift-config namespace to read support secret
# gather_support_secret.go
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    namespace: openshift-insights
    name: gather
roleRef:
  kind: ClusterRole
  name: multi-namespace-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
# Binding for openshift-ingress-operator namespace to read router-ca secret
# gather_cluster_ingress_certificates.go
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: openshift-ingress-operator
subjects:
  - kind: ServiceAccount
    namespace: openshift-insights
    name: gather
roleRef:
  kind: ClusterRole
  name: multi-namespace-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
# Binding for openshift-ingress namespace to read router-certs-default secret
# gather_cluster_ingress_certificates.go
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: openshift-ingress
subjects:
  - kind: ServiceAccount
    namespace: openshift-insights
    name: gather
roleRef:
  kind: ClusterRole
  name: multi-namespace-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
# Binding for openshift-kube-apiserver namespace to read revisioned secrets secret
# gather_revisioned_objects.go
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: openshift-kube-apiserver
subjects:
  - kind: ServiceAccount
    namespace: openshift-insights
    name: gather
roleRef:
  kind: ClusterRole
  name: multi-namespace-secret-reader
  apiGroup: rbac.authorization.k8s.io
