apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-insights
  name: trusted-ca-bundle
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Insights
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
