apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: report-overviews.external-pipeline.redhat.com
spec:
  group: external-pipeline.redhat.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                low:
                  type: integer
                moderate:
                  type: integer
                important:
                  type: integer
                critical:
                  type: integer
  scope: Cluster
  names:
    plural: report-overviews
    singular: report-overview
    kind: ReportOverview
    shortNames:
      - ro
