package main

var defaultDictionaryNames = `
activator
adapter
addon-operator-manager
addon-operator-webhook
adm
aggregator
agnhost
alertmanager
alibaba-cloud-controller-manager
alibaba-disk-csi-driver-operator
ansible-runner
apache
apicurito-ui
apiserver_receive_adapter
app
app-arm64.binary
app.binary
appender
applyconfig
app-ppc64le.binary
assisted-image-service
assisted-installer-controller
assisted-installer-controller-ocp
assisted-service
authentication-operator
autobumper
autoconfigbrancher
autoowners
autoperibolossync
autopublicizeconfig
autoscale
autoscaler
autoscaler-hpa
autotestgridgenerator
aws-cloud-controller-manager
aws-ebs-csi-driver
aws-ebs-csi-driver-operator
aws-efs-csi-driver
aws-efs-csi-driver-operator
aws-pod-identity-webhook
awssqs_receive_adapter
azure
azure-cloud-controller-manager
azure-cloud-node-manager
azure-disk-csi-driver-operator
azurediskplugin
azure-file-csi-driver-operator
azurefileplugin
backplane-operator
backport-verifier
base-usage
bash
blocking-issue-creator
boskosctl
bridge
broker-cleanup
broker_filter
broker_ingress
bugzilla-backporter
camel-source-controller
catalog
cephcsi
certmanager
channel_broker
channel_controller
channel_dispatcher
check_metadata_concealment
cinder-csi-plugin
clonerefs
cloud-credential-operator
cloud-event-proxy
cloud-ingress-operator
cluster-api-controller-manager
cluster-autoscaler
cluster-autoscaler-operator
cluster-baremetal-operator
cluster-bootstrap
cluster-capacity
cluster-config-operator
cluster-display
cluster-dns-operator
cluster-driver-registrar
cluster-etcd-operator
clusterimageset-updater
cluster-ingress-operator
cluster-init
cluster-kube-apiserver-operator
cluster-kube-controller-manager-operator
cluster-kube-scheduler-operator
cluster-kube-storage-version-migrator-operator
cluster-logging-operator
cluster-network-check-endpoints
cluster-network-check-target
cluster-network-operator
cluster-nfd-operator
cluster-node-tuning-operator
cluster-openshift-apiserver-operator
cluster-openshift-controller-manager-operator
cluster-operator
cluster-samples-operator
cluster-samples-operator-watch
cluster-storage-operator
cluster-version-operator
cm-adapter
cnftests
committed-offset
configmap-reload
configure-alertmanager-operator
console
console-operator
consolidated_controller
consolidated_dispatcher
consumer
container-entrypoint
contour
contour-operator
controller
controller-manager
coredns
coreos-diskimage-rehydrator
crd-schema-gen
create-efs-volume
creds-init
cronjob_receive_adapter
csi-attacher
csi-driver-projected-resource
csi-driver-shared-resource
csi-node-driver-registrar
csi-operator
csi-provisioner
csi-resizer
csi-snapshot-controller-operator
csi-snapshotter
curl
custom-domains-operator
default
descheduler
device-plugin-kvm
dex
diskmaker
distributed_controller
distributed_dispatcher
dns-operator
docker-entrypoint.sh
dockerregistry
domain-mapping
domain-mapping-webhook
dpcr-bugzilla-updater
dptp-controller-manager
dptp-pools-cm
driver-registrar
dumb-init
e2e.sh
e2e.test
echo
elasticsearch-operator
elasticsearch-proxy
emptydir
endpoint-monitoring-operator
entrypoint
entrypoint-bazel.sh
entrypoint-coverage
entrypoint-script.sh
entrypoint.sh
entrypoint-wrapper
environment
envvars
etcd
eventdetails
event_display
event-flaker
eventing-operator
event-library
eventlistenersink
eventrouter
event-sender
eventshub
events_scrape
exec
exports
external-dns
external-dns-operator
externaldns-operator
failing
fanoutsidecar
fetchdata.sh
file-integrity-logcollector
filter
filterevents
flaky
frr.sh
gangplank
gce-pd-csi-driver
gcp-cloud-controller-manager
gcp-pd-csi-driver-operator
gcppubsub_receive_adapter
gcs-fetcher
gcsweb
generate-registry-metadata
ghostunnel
github-ldap-user-group-creator
github-receive-adapter
github_receive_adapter
githubsource
github-source-controller
git-init
go-init
golangci-lint
grafana-dashboard-loader
grafana-server
graph-breaker
graph-builder
group-auto-updater
grpc-ping
gsutil
haproxy
heapster-wrapper.sh
heartbeats
heartbeats_receiver
hello
hellohttp2
hello-openshift
hellovolume
helloworld
helm-operator
help.sh
hook
host-operator
hostpathplugin
htmlproofer
httpd-foreground
httpproxy
hugo
hyperkube
hypershift
ibm-cloud-controller-manager
ibm-roks
ibm-vpc-block-csi-driver
ibm-vpc-block-csi-driver-operator
imc-controller
imc-dispatcher
ingress
ingress-operator
in-memory-channel-controller
in-memory-channel-dispatcher
insights-metrics
insights-operator
installer
interceptors
irb
istio
jenkins-operator
job-run-aggregator
job-trigger-controller-manager
jshell
k8sevents
kafka
kafka-ccp-channel-controller
kafka-ccp-channel-dispatcher
kafka-channel-controller
kafka-channel-crd-controller
kafka-channel-crd-dispatcher
kafka-channel-crd-webhook
kafka-channel-dispatcher
kafka-channel-webhook
kafka-consumer
kafka-controller
kafka_performance
kafka-publisher
kafka-source-adapter
kafka-source-controller
kafka_source_controller
kieserver-launch.sh
kn
koji-sane-json-api
kourier
kube-client-agent
kubeconfigwriter
kube-etcd-signer-server
kube-rbac-proxy
kuberneteseventsource
kube-scheduler
kube-state-metrics
kubevirt-csi-driver
kuryr-k8s-controller
latency
launcher
launch.sh
ldap-users-from-github-owners-files
leader-elector
libvirtd.sh
livenessprobe
loader
local-provisioner
local-server
local-storage-operator
logevents
loki
machine-api-operator
machine-approver
machine-config-controller
machine-config-daemon
machine-config-operator
machine-config-server
machine-controller-manager
machine-healthcheck
machineset-controller
main
managed-upgrade-operator
managed-velero-operator
management-ingress
manager
manila-csi-plugin
manila-provisioner
marketplace-operator
mco-operator
mdns-publisher
member-operator
member-operator-webhook
message_dumper
microshift
migrate
migrator
mock
monitor.sh
mounttest
mtbroker_filter
mtbroker_ingress
mtchannel_broker
mtcontroller
mtping
mtreceive_adapter
multiclusterhub-operator
multi-networkpolicy-iptables
must-gather-operator
mysql
mysqld
network-controller
network-metrics
nfsplugin
nfs-provisioner
nginx
nnp
node
node_exporter
node-feature-discovery-operator
nodelink-controller
noentry
nop
nscert
numaresources-operator
oauth-apiserver
oauth-proxy
oauth-server
observatorium
observed-concurrency
oc
ocs-operator
olm
openshift
openshift-acme-controller
openshift-acme-exposer
openshift-apiserver
openshift-apiserver-operator
openshift-aqua
openshift-authentication
openshift-authentication-operator
openshift-backplane
openshift-backplane-cee
openshift-backplane-managed-scripts
openshift-backplane-srep
openshift-build-test
openshift-cloud-credential-operator
openshift-cloud-ingress-operator
openshift-cluster-csi-drivers
openshift-cluster-machine-approver
openshift-cluster-node-tuning-operator
openshift-cluster-samples-operator
openshift-cluster-storage-operator
openshift-cluster-version
openshift-codeready-workspaces
openshift-config
openshift-config-managed
openshift-config-operator
openshift-console
openshift-console-operator
openshift-console-user-settings
openshift-controller-manager
openshift-controller-manager-operator
openshift-custom-domains-operator
openshift-customer-monitoring
openshift-debug-node-5nlfmqqk76
openshift-debug-node-956rgqjx88
openshift-debug-node-crb5jddvgw
openshift-debug-node-hthmftkfmv
openshift-deploy
openshift-dns
openshift-dns-operator
openshift-docker-build
openshift-etcd
openshift-etcd-operator
openshift-f5-router
openshift-host-network
openshift-image-registry
openshift-infra
openshift-ingress
openshift-ingress-canary
openshift-ingress-operator
openshift-insights
openshift-install
openshift-kni-infra
openshift-kube-apiserver
openshift-kube-apiserver-operator
openshift-kube-controller-manager
openshift-kube-controller-manager-operator
openshift-kube-scheduler
openshift-kube-scheduler-operator
openshift-kube-storage-version-migrator
openshift-kube-storage-version-migrator-operator
openshift-launch.sh
openshift-logging
openshift-machine-api
openshift-machine-config-operator
openshift-managed-upgrade-operator
openshift-marketplace
openshift-monitoring
openshift-multus
openshift-must-gather-operator
openshift-network-diagnostics
openshift-network-operator
openshift-node
openshift-oauth-apiserver
openshift-openstack-infra
openshift-operator-lifecycle-manager
openshift-operators
openshift-operators-redhat
openshift-osd-metrics
openshift-ovirt-infra
openshift-priv
openshift-psap
openshift-rbac-permissions
openshift-recycle
openshift-route-monitor-operator
openshift-router
openshift-sdn
openshift-security
openshift-service-ca
openshift-service-ca-operator
openshift-service-catalog-removed
openshift-splunk-forwarder-operator
openshift-sre-pruning
openshift-state-metrics
openshift-strimzi
openshift-user-workload-monitoring
openshift-validation-webhook
openshift-velero
openshift-vsphere-infra
openstack-cinder-csi-driver-operator
openstack-cloud-controller-manager
operator
operator-sdk
opm
origin-node-run.sh
origin-web-console
osd-metrics-exporter
osin-operator
ovirt-csi-driver
ovirt-csi-driver-operator
package-server
partitions-replication-verifier
pause
payload-testing-prow-plugin
payload-testing-ui
performance
performance-operator
perl5.26.3
php
ping
pingsource-cleanup
pj-rehearse
plank
pod
pod-scaler
pong
postgres
post-install
pqsql
prcreator
preflight
print
printport
private-org-peribolos-sync
private-org-sync
private-prow-configs-mirror
profiles
prometheus
prometheus-config-reloader
prom-kube-proxy
prom-label-proxy
promtail
protocols
ptp
ptp-operator
publicize
pytest.sh
python
python3
python3.9
qemu-ga
queue
rbac-permissions-operator
rbac-query-proxy
readiness
receive_adapter
receiver
recordevents
redis
redis-server
reference-addon-manager
registration-service
registry
registry-replacer
registry-server
repo-brancher
repo-init
reporting-operator
request-sender
resource-topology-exporter
result-aggregator
resultscollector
resultserver
roxctl-linux
rsyslog.sh
rte-operator
run
run-docker-tests.sh
run_gluster.sh
run-httpd
runironic
runironic-agent
runironicagent
runironic-inspector
run_iscsi_target.sh
run-jnlp-client
run-mongod
run-mysqld
run_nfs.sh
run-openldap.sh
run-operator.sh
run-postgresql
run-redis
run.sh
run-test-image.sh
run-tests.sh
run_tests.sh
runtime
runtimecfg
runtime-unprivileged
s2i
sanitize-prow-jobs
schedule-generator
schema
scl
sctptest
search
secret-wrapper
security-profiles-operator
sendevent
sendevents
sequencestepper
server
serviceaccount-secret-rotation-trigger
service-ca-operator
service-catalog
servingcontainer
serving-operator
setup-etcd-environment
sh
shared-resources-operator
sidecar
sidecarcontainer
singlethreaded
smart_exporter
snapshot-controller
snapshot-provisioner
snapshot-validation-webhook
source_controller
sources_controller
special-resource-operator
spectral
splunk-forwarder-operator
sprint-automation
sriov-network-config-daemon
sriov-network-operator
sshd
start
start-cypress-tests.sh
start-tests.sh
--storage.path
subscription-injection-webhook
sugar_controller
support-operator
telemeter-client
template-deprecator
template-service-broker
testgrid-config-generator
test-run.sh
test.sh
test-webserver
thanos
timeout
tini
toolchain-operator
tox
transformevents
true
usage
-vault-addr
vault-secret-collection-manager
vault-subpath-proxy
vector
velero
vertical-pod-autoscaler-operator
virt-api
virt-controller
virt-handler
virt-launcher
virt-operator
vmware-vsphere-csi-driver
vmware-vsphere-csi-driver-operator
vmware-vsphere-csi-driver-syncer
vsphere-cloud-controller-manager
vsphere-problem-detector
wathola-fetcher
wathola-forwarder
wathola-kafka-sender
wathola-receiver
wathola-sender
webhook
webhook-kafka
webhooks
websocketsource
winmachineman
winoperatordata
workingdir
workload-app
wsserver
`
